name: Pre-release Build Validation Scripts

on: 
  push:
    branches:
      - jhurne/experiment-automation
  workflow_dispatch:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: jhurne/experiment-automation
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      -  name: Build with Gradle
         uses: eskatos/gradle-command-action@v1.3.3
         with:
           arguments: build
           wrapper-cache-enabled: true
           dependencies-cache-enabled: true
           configuration-cache-enabled: false
           build-root-directory: build-validation/distribution-build
           wrapper-directory: build-validation/distribution-build
      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "build-validation-development-latest"
          prerelease: true
          title: "Build Validation - Development Build"
          files: "build-validation/distribution-build/build/distributions/*.zip"

